name: Run Python Script Daily

on:
  schedule:
    # Runs daily at 3:00 AM UTC
    - cron: '0 3 * * *'
  push:
    branches:
      - main
      - metrics
  workflow_dispatch:  # Allows manual triggers

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.NEW_GCP_JSON }}

    - name: Run Python script
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python experiments/metrics/exp446_metrics.py  
