name: Verify pipeline with quickstart script

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pip dependencies
        run: |
          pip install '.[dev]'

      - name: List installed pip packages
        run: |
          pip list

      - name: Verify installation
        run: |
          python -c "import draccus" || echo 'draccus not installed'
          python -c "import ray" || echo 'ray not installed'
          
      - name: Start Ray cluster locally
        run: |
          ray start --head

      - name: Test quickstart pipeline
        run: |
          ray job submit --working-dir . -- python experiments/quickstart-synthetic.py --commit_hash exp-${{ github.sha }}
