name: Verify pipeline with quickstart script

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install .["dev"] --extra-index-url https://download.pytorch.org/whl/cpu
          pip install ray[default]==2.34.0
          
      - name: Start Ray cluster locally
        run: |
          ray start --head

      - name: Test quickstart pipeline
        run: |
          ray job submit --working-dir . -- python experiments/quickstart-synthetic.py --commit_hash exp-${{ github.sha }}