name: Verify pipeline with quickstart script

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip dependencies
        uses: actions/cache@v3
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-verify-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-verify-

      - name: Install pip dependencies
        shell: bash -l {0}
        run: |
          pip install .["dev"] 
          
      - name: Install other dependencies
        shell: bash -l {0}
        run: |
          pip install ray[default]==2.34.0 --extra-index-url https://download.pytorch.org/whl/cpu
          pip install pytest>=8.3.2
          
      - name: Start Ray cluster locally
        shell: bash -l {0}
        run: |
          ray start --head

      - name: Test quickstart pipeline
        shell: bash -l {0}
        run: |
          ray job submit --working-dir . -- python experiments/quickstart-synthetic.py --commit_hash exp-${{ github.sha }}
