name: Verify pipeline with quickstart script

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: marin_quickstart_env
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install .["dev"] --extra-index-url https://download.pytorch.org/whl/cpu
          pip install ray[default]==2.34.0 
          
      - name: Start Ray cluster locally
        shell: bash -l {0}
        run: |
          ray start --head

      - name: Test quickstart pipeline
        shell: bash -l {0}
        run: |
          ray job submit --working-dir . -- python experiments/quickstart-synthetic.py --commit_hash exp-${{ github.sha }}
