name: Verify PR with quickstart.py

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - main
  pull_request_review:
    types: [submitted, dismissed]
  issue_comment:
    types: [created]
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Only run on approval for pull_request_review submitted events or specific comment trigger
    if: |
      if: github.event_name == 'push' || 
        github.event.review.state == 'approved' && github.event.action == 'submitted' ||
        github.event.action == 'dismissed' || 
        (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@run-quickstart-ci'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -e ".[dev]"

      - name: Start Ray cluster locally
        run: |
          ray start --head

      - name: Test quickstart pipeline
        run: |
          ray job submit --working-dir . -- python experiments/quickstart-synthetic.py --commit_hash exp-${{ github.sha }}