name: Verify PR with quickstart.sh

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Install Ray
      run: |
        pip install ray[default]
        pip install google-api-python-client

    - name: Connect to Ray cluster on GCP in the background
      run: |
        ray start --head

    - name: Run quickstart.sh
      run: |
        bash experiments/quickstart.sh