name: Verify PR with quickstart.py

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: marin_quickstart_env
          auto-activate-base: false

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-12 g++-12 libnuma-dev libdnnl-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12

      - name: Install Python dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge libstdcxx-ng
          pip install wheel packaging ninja "setuptools>=49.4.0" numpy setuptools_scm
          pip install -U jax==0.4.31
          git clone https://github.com/stanford-crfm/levanter.git && cd levanter
          pip install .[test]
          cd ../

      - name: Clone and build vLLM
        shell: bash -l {0}
        run: |
          git clone https://github.com/vllm-project/vllm.git
          cd vllm
          pip install -v -r requirements-cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu
          VLLM_TARGET_DEVICE=cpu python setup.py install
          cd ..

      - name: Clone and install HELM with local_vllm branch
        shell: bash -l {0}
        run: |
          git clone -b local_vllm https://github.com/stanford-crfm/helm.git
          cd helm
          pip install .
          cd ..

      - name: Install additional dependencies
        shell: bash -l {0}
        run: |
          pip install . --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Start Ray cluster locally
        shell: bash -l {0}
        run: |
          ray start --head

      - name: Test quickstart pipeline
        shell: bash -l {0}
        run: |
          ray job submit --working-dir . \
                  --runtime-env-json='{"excludes": ["**/.git/**", ".gitattributes"]}' \   
                  -- python experiments/quickstart-synthetic.py --commit_hash exp-${{ github.sha }}
