name: Run unit tests

on: 
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - main
  pull_request_review:
    types: [submitted, dismissed]
  issue_comment:
    types: [created]
  push:
    branches:
      - main

jobs:
  test:
    if: github.event_name == 'push' || 
        github.event.review.state == 'approved' && github.event.action == 'submitted' ||
        github.event.action == 'dismissed' || 
        (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@run-unit-tests'))

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.12"]
        node-version: ["20.10.0"]
        jax-version: [ "0.4.26" ]

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: marin_unit_test_env
          auto-activate-base: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pandoc
          npm install -g pandiff
          pip install -e ".[dev]" "jax[cpu]==${{ matrix.jax-version }}" "jaxlib==${{ matrix.jax-version }}"
          pip install ray[default] google-api-python-client
          
      - name: Start Ray cluster locally
        shell: bash -l {0}
        run: |
          ray start --head

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          PYTHONPATH=tests:. pytest --tb=no -v