name: Run unit tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.12"]
        node-version: ["20.10.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: marin_unit_test_env
          auto-activate-base: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-unittest-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-unittest-

      - name: Install pip dependencies
        run: |
          pip install '.[dev]'
          pip install ray[default] google-api-python-client pytest>=8.3.2
         
      - name: Other dependencies
        run: |
          conda install -c conda-forge pandoc
          npm install -g pandiff 
          
      - name: Start Ray cluster locally
        run: |
          ray start --head

      - name: Test with pytest
        run: |
          PYTHONPATH=tests:. pytest --tb=no -v
