name: Run unit tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.12"]
        node-version: ["20.10.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: marin_unit_test_env
          auto-activate-base: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pandoc
          npm install -g pandiff
          pip install . --extra-index-url https://download.pytorch.org/whl/cpu
          
      - name: Start Ray cluster locally
        shell: bash -l {0}
        run: |
          ray start --head

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          PYTHONPATH=tests:. pytest --tb=no -v
