name: Update Speedrun Leaderboard

on:
  pull_request:
    paths:
      - 'experiments/speedrun/**'
    types: [opened, synchronize]

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fsspec gcsfs

    - name: Update leaderboard
      run: |
        cd experiments/speedrun
        python update_leaderboard.py --gcs-path gs://marin-us-central2/checkpoints/speedrun --print-only > leaderboard_update.txt

    - name: Check for changes
      id: check_changes
      run: |
        cd experiments/speedrun/static/data
        if [[ -f leaderboard.json ]]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Comment on PR
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const leaderboardUpdate = fs.readFileSync('experiments/speedrun/leaderboard_update.txt', 'utf8');
          const leaderboardData = JSON.parse(fs.readFileSync('experiments/speedrun/static/data/leaderboard.json', 'utf8'));
          
          let comment = '## 🏃 Speedrun Leaderboard Update\n\n';
          comment += 'Your PR has triggered a leaderboard update. Here are the current standings:\n\n';
          comment += '```\n' + leaderboardUpdate + '\n```\n\n';
          
          // Add details about the new entry
          const newEntry = leaderboardData.find(e => e.run_name.includes(context.payload.pull_request.head.ref));
          if (newEntry) {
            comment += '### Your Submission Details:\n';
            comment += `- **Run Name**: ${newEntry.run_name}\n`;
            comment += `- **Track**: ${newEntry.compute_budget_track}\n`;
            comment += `- **Model Size**: ${newEntry.model_size}\n`;
            comment += `- **Training Time**: ${newEntry.total_training_time.toFixed(1)}m\n`;
            comment += `- **FLOPs Used**: ${newEntry.final_flops_used.toExponential(2).replace('e+', 'E')}\n`;
          }
          
          comment += '\nView the full leaderboard at: https://stanford-crfm.github.io/marin/speedrun/';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
